format_version: v1.0
type: UniqueComponent
attributes: {id: dbgu}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '108'}
  - type: Comment
    attributes: {id: DBGU_CLK_ENABLE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: DBGU_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: dbgu, value: '200000000'}
- type: ElementPosition
  attributes: {x: '340', y: '20', id: dbgu}
