format_version: v1.0
type: UniqueComponent
attributes: {id: pwm}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CH0_CALG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH0_CDTY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '100'}
  - type: KeyValueSet
    attributes: {id: CH0_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH0_CPRD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1000'}
  - type: Boolean
    attributes: {id: CH0_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CH0_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '1000000'}
  - type: Comment
    attributes: {id: CH0_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 1000.0 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH0_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '11'}
  - type: Integer
    attributes: {id: CH1_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '0'}
  - type: Integer
    attributes: {id: CH2_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '0'}
  - type: Integer
    attributes: {id: CH3_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '0'}
  - type: Integer
    attributes: {id: CLKA_DIV}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '200'}
  - type: Boolean
    attributes: {id: CLKA_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CLKA_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '1000000'}
  - type: KeyValueSet
    attributes: {id: CLKA_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '100', y: '133', id: pwm}
