configName: sam_9x60_ek_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\Projects\mpu
processor: SAM9X60
projectName: random_number_sam_9x60_ek_iar
settings:
  PackageFilter: bsp;core;csp;csp_apps_sam_9x60;csp_apps_sam_a5d2
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.5.49\atdf\SAM9X60.atdf
  MERGE_STRATEGY: OVERWRITE
