format_version: v1.0
type: UniqueComponent
attributes: {id: shdwc}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: PINS_LIST}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: shdwc, value: ' WKUPEN0'}
  - type: KeyValueSet
    attributes: {id: WKUPDBC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Boolean
    attributes: {id: WKUPEN0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '500', y: '20', id: shdwc}
