format_version: v1.0
type: UniqueComponent
attributes: {id: pwm}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CH0_CALG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH0_CDTY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2500'}
  - type: KeyValueSet
    attributes: {id: CH0_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: CH0_CPRD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10000'}
  - type: Boolean
    attributes: {id: CH0_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CH0_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '10000000'}
  - type: Comment
    attributes: {id: CH0_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 1000.0 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH0_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '11'}
  - type: KeyValueSet
    attributes: {id: CH1_CALG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: CH1_CDTY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '25000'}
  - type: KeyValueSet
    attributes: {id: CH1_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: CH1_CPRD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '50000'}
  - type: Boolean
    attributes: {id: CH1_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CH1_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '10000000'}
  - type: Comment
    attributes: {id: CH1_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 100.0 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH1_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '12'}
  - type: KeyValueSet
    attributes: {id: CH2_CALG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: CH2_CDTY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '3750000'}
  - type: KeyValueSet
    attributes: {id: CH2_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: CH2_CPRD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '5000000'}
  - type: Boolean
    attributes: {id: CH2_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CH2_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '50000000'}
  - type: Comment
    attributes: {id: CH2_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 10.0 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH2_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: KeyValueSet
    attributes: {id: CH3_CALG}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH3_CDTY}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '25000000'}
  - type: KeyValueSet
    attributes: {id: CH3_CPOL}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: CH3_CPRD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '25000000'}
  - type: Boolean
    attributes: {id: CH3_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CH3_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '25000000'}
  - type: Boolean
    attributes: {id: CH3_IER_CHID}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: CH3_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '**** PWM Frequency is 1.0 Hz ****'}
  - type: KeyValueSet
    attributes: {id: CH3_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '3'}
  - type: Integer
    attributes: {id: CLKA_DIV}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '5'}
  - type: Boolean
    attributes: {id: CLKA_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CLKA_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '10000000'}
  - type: KeyValueSet
    attributes: {id: CLKA_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: CLKB_DIV}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Boolean
    attributes: {id: CLKB_EN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: CLKB_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pwm, value: '10000000'}
  - type: KeyValueSet
    attributes: {id: CLKB_PRES}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '148', y: '138', id: pwm}
