configName: sam_9x60_ek
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: SAM9X60
projectName: ''
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;micrium_ucos3;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.1.28\atdf\SAM9X60.atdf
  MERGE_STRATEGY: USER_ALL
