files:
- generatedChecksum: 6FB632CFBE9592AC014B65AFBA27AFE8
  logicalPath: config\sam_9x60_ek
  name: cstartup.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6FB632CFBE9592AC014B65AFBA27AFE8
- generatedChecksum: 6D05FB9478FD7E069AA15FBA0C30C8CB
  logicalPath: config\sam_9x60_ek
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6D05FB9478FD7E069AA15FBA0C30C8CB
- generatedChecksum: 8801C64248969E22DB79B96B90E009FA
  logicalPath: config\sam_9x60_ek
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8801C64248969E22DB79B96B90E009FA
- generatedChecksum: F81A00E640818EDFB9E79C9BD241AEF4
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: F81A00E640818EDFB9E79C9BD241AEF4
- generatedChecksum: E9F39FD27254B4FB48793116074DC8AC
  logicalPath: config\sam_9x60_ek\peripheral\aic
  name: plib_aic.c
  physicalPath: peripheral\aic
  security: NON_SECURE
  type: SOURCE
  userChecksum: E9F39FD27254B4FB48793116074DC8AC
- generatedChecksum: C63E527A0C47997A1E2F8A25C72CA85C
  logicalPath: config\sam_9x60_ek\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: C63E527A0C47997A1E2F8A25C72CA85C
- generatedChecksum: 99A28DC2A2D39E2B47E46E62E0C710D6
  logicalPath: config\sam_9x60_ek\peripheral\mmu
  name: plib_mmu.c
  physicalPath: peripheral\mmu
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99A28DC2A2D39E2B47E46E62E0C710D6
- generatedChecksum: E188AA0A5688669D11F2B0B1C7176A0E
  logicalPath: config\sam_9x60_ek\peripheral\pio
  name: plib_pio.c
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: SOURCE
  userChecksum: E188AA0A5688669D11F2B0B1C7176A0E
- generatedChecksum: 97434B1A8170A7E29EA666D55FF3F212
  logicalPath: config\sam_9x60_ek
  name: vectortrap.s
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 97434B1A8170A7E29EA666D55FF3F212
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\sam_9x60_ek\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 98F5E5CACA4CF661F7DE3579EE624B22
  logicalPath: packs\SAM9X60_DFP\component
  name: adc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 98F5E5CACA4CF661F7DE3579EE624B22
- generatedChecksum: 16EFCA06C42544B87E6F892FDC73643E
  logicalPath: packs\SAM9X60_DFP\component
  name: aes.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 16EFCA06C42544B87E6F892FDC73643E
- generatedChecksum: D3DCED31A905B90D378761682481B831
  logicalPath: packs\SAM9X60_DFP\component
  name: aic.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D3DCED31A905B90D378761682481B831
- generatedChecksum: B99C6B9DB54ECBCE44A858677ADCBD9D
  logicalPath: packs\SAM9X60_DFP\component
  name: bsc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B99C6B9DB54ECBCE44A858677ADCBD9D
- generatedChecksum: FB4FB566A473FD25CA97A6CF681159AC
  logicalPath: packs\SAM9X60_DFP\component
  name: can.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: FB4FB566A473FD25CA97A6CF681159AC
- generatedChecksum: 66801034BEA630B248EBB1FD69AEDA6C
  logicalPath: packs\SAM9X60_DFP\component
  name: classd.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 66801034BEA630B248EBB1FD69AEDA6C
- generatedChecksum: 8B35997040E0D61B0C62411FF7C4E9C1
  logicalPath: config\sam_9x60_ek\peripheral\mmu
  name: cp15.h
  physicalPath: peripheral\mmu
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B35997040E0D61B0C62411FF7C4E9C1
- generatedChecksum: 2ADD9442607942235FFD134CC98F8F5C
  logicalPath: packs\SAM9X60_DFP\component
  name: dbgu.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 2ADD9442607942235FFD134CC98F8F5C
- generatedChecksum: E82CCC815B43A8EE9003C570397E876C
  logicalPath: config\sam_9x60_ek
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E82CCC815B43A8EE9003C570397E876C
- generatedChecksum: 46C77E8D13EE53B3310B0E2DFC092D92
  logicalPath: config\sam_9x60_ek
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 46C77E8D13EE53B3310B0E2DFC092D92
- generatedChecksum: 7254700FC13F4B4E1929CADEB2F317FE
  logicalPath: config\sam_9x60_ek
  name: device_cache.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7254700FC13F4B4E1929CADEB2F317FE
- generatedChecksum: B4720A5923029809BD4F8924B9150287
  logicalPath: packs\SAM9X60_DFP\component
  name: emac.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B4720A5923029809BD4F8924B9150287
- generatedChecksum: 1E6DD1752D265D073C1DBE8E165F55D3
  logicalPath: packs\SAM9X60_DFP\component
  name: flexcom.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E6DD1752D265D073C1DBE8E165F55D3
- generatedChecksum: D76F2C976157119DF8F9B8F2877ADD86
  logicalPath: packs\SAM9X60_DFP\component
  name: gfx2d.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: D76F2C976157119DF8F9B8F2877ADD86
- generatedChecksum: 59BD12E622614028FE90E76DF6E17A63
  logicalPath: packs\SAM9X60_DFP\component
  name: gpbr.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 59BD12E622614028FE90E76DF6E17A63
- generatedChecksum: ED49BC621E8F4B4516A5BB6331E90E7B
  logicalPath: packs\SAM9X60_DFP\component
  name: i2smcc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: ED49BC621E8F4B4516A5BB6331E90E7B
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\sam_9x60_ek
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: C084C2A37C9C916181F60F14AB4E758E
  logicalPath: packs\SAM9X60_DFP\component
  name: isi.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C084C2A37C9C916181F60F14AB4E758E
- generatedChecksum: B720E929D8F2AECFDC7B5EF2D52DC80F
  logicalPath: packs\SAM9X60_DFP\component
  name: lcdc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B720E929D8F2AECFDC7B5EF2D52DC80F
- generatedChecksum: 4D4A00EB1F506EB06833CA4E27E74016
  logicalPath: packs\SAM9X60_DFP\component
  name: matrix.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D4A00EB1F506EB06833CA4E27E74016
- generatedChecksum: A698247047F56324C05217DB6006E9D3
  logicalPath: packs\SAM9X60_DFP\component
  name: mpddrc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A698247047F56324C05217DB6006E9D3
- generatedChecksum: B2BD40DCA2AE55C3EEF4AF8EC3321256
  logicalPath: packs\SAM9X60_DFP\component
  name: otpc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B2BD40DCA2AE55C3EEF4AF8EC3321256
- generatedChecksum: 5B679C1BF6286EED876A8626AF5E4859
  logicalPath: packs\SAM9X60_DFP\component
  name: pio.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5B679C1BF6286EED876A8626AF5E4859
- generatedChecksum: 4917F0A86C683445B577A12469AA6EBE
  logicalPath: packs\SAM9X60_DFP\component
  name: pit.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4917F0A86C683445B577A12469AA6EBE
- generatedChecksum: 352B93E129F8C2A93CBFB5AF572A9E3D
  logicalPath: packs\SAM9X60_DFP\component
  name: pit64b.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 352B93E129F8C2A93CBFB5AF572A9E3D
- generatedChecksum: 9C00DC189B706ECF854F34A404F89118
  logicalPath: config\sam_9x60_ek\peripheral\aic
  name: plib_aic.h
  physicalPath: peripheral\aic
  security: NON_SECURE
  type: HEADER
  userChecksum: 9C00DC189B706ECF854F34A404F89118
- generatedChecksum: A8C5DBCE5B68F9E4B9078E54DC2B2FEA
  logicalPath: config\sam_9x60_ek\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: A8C5DBCE5B68F9E4B9078E54DC2B2FEA
- generatedChecksum: 53692CB5F4391E126593D39BD431C323
  logicalPath: config\sam_9x60_ek\peripheral\mmu
  name: plib_mmu.h
  physicalPath: peripheral\mmu
  security: NON_SECURE
  type: HEADER
  userChecksum: 53692CB5F4391E126593D39BD431C323
- generatedChecksum: D81EF5AA93C09ADD45D80F9E2247E9FB
  logicalPath: config\sam_9x60_ek\peripheral\pio
  name: plib_pio.h
  physicalPath: peripheral\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: D81EF5AA93C09ADD45D80F9E2247E9FB
- generatedChecksum: 1E7E39A6AFC1F5078B627AF8AB33E030
  logicalPath: packs\SAM9X60_DFP\component
  name: pmc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1E7E39A6AFC1F5078B627AF8AB33E030
- generatedChecksum: 3832397C62FD892502809D2BD1B27250
  logicalPath: packs\SAM9X60_DFP\component
  name: pmecc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 3832397C62FD892502809D2BD1B27250
- generatedChecksum: 6441D0B66979DBA5A5F76A01CE620418
  logicalPath: packs\SAM9X60_DFP\component
  name: pmerrloc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6441D0B66979DBA5A5F76A01CE620418
- generatedChecksum: 6C49531EC91091953DD36DF71A849287
  logicalPath: packs\SAM9X60_DFP\component
  name: pwm.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6C49531EC91091953DD36DF71A849287
- generatedChecksum: 5B5D7CB292CE63DE21F9CEAD30DC4DC4
  logicalPath: packs\SAM9X60_DFP\component
  name: qspi.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5B5D7CB292CE63DE21F9CEAD30DC4DC4
- generatedChecksum: F862B8FB0A428B5BF2C49D8B70F7B092
  logicalPath: packs\SAM9X60_DFP\component
  name: rstc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: F862B8FB0A428B5BF2C49D8B70F7B092
- generatedChecksum: 6ADBABB95AF3EC8D0E7AFA67A6D41A21
  logicalPath: packs\SAM9X60_DFP\component
  name: rtc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 6ADBABB95AF3EC8D0E7AFA67A6D41A21
- generatedChecksum: 9BACB1F01E3ECEE4BE3051124DC5737B
  logicalPath: packs\SAM9X60_DFP\component
  name: rtt.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9BACB1F01E3ECEE4BE3051124DC5737B
- generatedChecksum: 589982FC2C6FD68356859C0B693B54CA
  logicalPath: packs\SAM9X60_DFP
  name: sam9x60.h
  physicalPath: ..\..\packs\SAM9X60_DFP
  security: NON_SECURE
  type: HEADER
  userChecksum: 589982FC2C6FD68356859C0B693B54CA
- generatedChecksum: 9A6D33394545A78F300C6DEC4194F532
  logicalPath: packs\SAM9X60_DFP\pio
  name: sam9x60.h
  physicalPath: ..\..\packs\SAM9X60_DFP\pio
  security: NON_SECURE
  type: HEADER
  userChecksum: 9A6D33394545A78F300C6DEC4194F532
- generatedChecksum: B10E8FDF3FFE2BCE5138599175A18508
  logicalPath: packs\SAM9X60_DFP\component
  name: sckc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B10E8FDF3FFE2BCE5138599175A18508
- generatedChecksum: 4AE1C87D8EB4DA6EF7E0BDF587FD7EFE
  logicalPath: packs\SAM9X60_DFP\component
  name: sdmmc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 4AE1C87D8EB4DA6EF7E0BDF587FD7EFE
- generatedChecksum: 71BA8CA9BDD075F6852E7DE12D0B9918
  logicalPath: packs\SAM9X60_DFP\component
  name: sdramc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 71BA8CA9BDD075F6852E7DE12D0B9918
- generatedChecksum: 548534418BB668A995369EA2C2631EBB
  logicalPath: packs\SAM9X60_DFP\component
  name: sfr.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 548534418BB668A995369EA2C2631EBB
- generatedChecksum: 69AFF83B1AB848A66385F724BDAD5C70
  logicalPath: packs\SAM9X60_DFP\component
  name: sha.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 69AFF83B1AB848A66385F724BDAD5C70
- generatedChecksum: 9B013FD35FC4759BCDED8D56981B0E3B
  logicalPath: packs\SAM9X60_DFP\component
  name: shdwc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B013FD35FC4759BCDED8D56981B0E3B
- generatedChecksum: 7DC14940A2FE2AAD1CAC3D3DEE6D9236
  logicalPath: packs\SAM9X60_DFP\component
  name: smc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC14940A2FE2AAD1CAC3D3DEE6D9236
- generatedChecksum: BDB0AC1DCA848B361D4BB43CFFC16EBF
  logicalPath: packs\SAM9X60_DFP\component
  name: ssc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: BDB0AC1DCA848B361D4BB43CFFC16EBF
- generatedChecksum: E5553A331056D1F3A32188CF8E8F4547
  logicalPath: packs\SAM9X60_DFP\component
  name: syscwp.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: E5553A331056D1F3A32188CF8E8F4547
- generatedChecksum: B2B8DF81AACE9D4D767C45BB48ECCEAE
  logicalPath: packs\SAM9X60_DFP\component
  name: tc.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B2B8DF81AACE9D4D767C45BB48ECCEAE
- generatedChecksum: C7C710278C2D5F0F1E1F6558066CA340
  logicalPath: packs\SAM9X60_DFP\component
  name: tdes.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: C7C710278C2D5F0F1E1F6558066CA340
- generatedChecksum: C0A13F5280AE3C6140103C178B189214
  logicalPath: config\sam_9x60_ek
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: C0A13F5280AE3C6140103C178B189214
- generatedChecksum: 5C6352DB1DD121F0F347F64C7DB36B21
  logicalPath: packs\SAM9X60_DFP\component
  name: trng.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5C6352DB1DD121F0F347F64C7DB36B21
- generatedChecksum: 5A05B014254745B975419DAE7E71C91D
  logicalPath: packs\SAM9X60_DFP\component
  name: udphs.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 5A05B014254745B975419DAE7E71C91D
- generatedChecksum: 83ED5B4A57472B9BEA8E69AE3C44C642
  logicalPath: packs\SAM9X60_DFP\component
  name: uhpfs.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 83ED5B4A57472B9BEA8E69AE3C44C642
- generatedChecksum: 1CFB14BA718B0754E95BCEA45389F9D8
  logicalPath: packs\SAM9X60_DFP\component
  name: uhphs.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: 1CFB14BA718B0754E95BCEA45389F9D8
- generatedChecksum: A8C9C60DF3599E65699C96C7288EFBC4
  logicalPath: packs\SAM9X60_DFP\component
  name: wdt.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: A8C9C60DF3599E65699C96C7288EFBC4
- generatedChecksum: B8FF0AA145D753A08F48ABE7F69E2BA5
  logicalPath: packs\SAM9X60_DFP\component
  name: xdmac.h
  physicalPath: ..\..\packs\SAM9X60_DFP\component
  security: NON_SECURE
  type: HEADER
  userChecksum: B8FF0AA145D753A08F48ABE7F69E2BA5
- generatedChecksum: CF7BFA804A96A03FD789AA98C72C51DD
  logicalPath: config\sam_9x60_ek
  name: ddram.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: CF7BFA804A96A03FD789AA98C72C51DD
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_9x60_ek;../src/packs/SAM9X60_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ROM_ORIGIN=0x0x23f00000;ROM_LENGTH=-0x23f00000
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/sam_9x60_ek;../src/packs/SAM9X60_DFP;../src/packs/CMSIS/CMSIS/Core/Include;../src/packs/CMSIS/
sourcePaths: []
