configName: sam_9x60_ek
folderName: sam_9x60_ek
format_version: v1.0
frameworkPath: ..\..\..\..
processor: SAM9X60
projectName: sam_9x60_ek
settings:
  PackageFilter: bsp;core;csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: OVERWRITE
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.5.49\atdf\SAM9X60.atdf
