configName: sam_9x60_ek_iar
folderName: ''
format_version: v1.0
frameworkPath: D:\MCU_MPU\SAMA5\H3_MPU
processor: SAM9X60
projectName: can_normal_operation_blocking_sam_9x60_ek_iar
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.0.20\atdf\SAM9X60.atdf
