configName: sam_9x60_curiosity
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: SAM9X60D1G
projectName: ''
settings:
  PackageFilter: bsp;core;csp;expresslogic_threadx;net;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAM9X60_DFP\1.1.23\atdf\SAM9X60D1G.atdf
